In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('data/sales_data.csv')

Initial Data inspection

In [6]:
print(f"Starting shape: {df.shape}")

Starting shape: (600, 9)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            600 non-null    str
 1   transaction_id  600 non-null    str
 2   product_id      600 non-null    str
 3   product_name    600 non-null    str
 4   category        600 non-null    str
 5   store           600 non-null    str
 6   quantity        599 non-null    float64
 7   unit_price      600 non-null    str
 8   payment_method  600 non-null    str
dtypes: float64(1), str(8)
memory usage: 42.3 KB

In [8]:
df.head()

,date,transaction_id,product_id,product_name,category,store,quantity,unit_price,payment_method
0,2026-01-31,T1000,P006,Full Cream Milk 2L,Dairy,Sandton,9.0,34.0,Cash
1,2026-06-03,T1001,P010,Beef Mince 1kg,Meat,Pretoria,9.0,135.0,Mobile
2,2026-05-31,T1002,P008,Tomatoes 1kg,Produce,Sandton,4.0,30.0,Card
3,2026-01-29,T1003,P005,Cheddar Cheese 500g,Dairy,Sandton,14.0,95.0,Mobile
4,2026-01-03,T1004,P008,Tomatoes 1kg,Produce,Soweto,11.0,30.0,Cash

In [9]:
df.isna().sum()

date              0
transaction_id    0
product_id        0
product_name      0
category          0
store             0
quantity          1
unit_price        0
payment_method    0
dtype: int64

In [10]:
df.describe()

         quantity
count  599.000000
mean     7.766277
std      4.301994
min     -3.000000
25%      4.000000
50%      8.000000
75%     11.000000
max     15.000000